// Demonstrate check boxes.

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;

public class CBDemo implements ItemListener, ActionListener {

  JButton jbtn;
  JLabel jlabSelected, jlabChanged, jlabSum;
  JCheckBox jcbAlpha, jcbBeta, jcbGamma;

  CBDemo() {
    // Create a new JFrame container.
    JFrame jfrm = new JFrame("Demonstrate Check Boxes");

    // Specify FlowLayout for the layout manager.
    jfrm.setLayout(new FlowLayout());

    // Give the frame an initial size.
    jfrm.setSize(300, 150);

    // Terminate the program when the user closes the application.
    jfrm.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    // Create empty labels.
    jlabSelected = new JLabel("");
    jlabChanged = new JLabel("");
    jlabSum = new JLabel("");

    // Make change boxes.
    jcbAlpha = new JCheckBox("Alpha");
    jcbBeta = new JCheckBox("Beta");
    jcbGamma = new JCheckBox("Gamma");

    // Make button.
    jbtn = new JButton("Sum");

    // Events generated by the check boxes are handled
    // in common by the itemStateChanged() method
    // implemented by CBDemo.
    jcbAlpha.addItemListener(this);
    jcbBeta.addItemListener(this);
    jcbGamma.addItemListener(this);
    jbtn.addActionListener(this);

    // Add check boxes and labels to the content pane.
    jfrm.add(jcbAlpha);
    jfrm.add(jcbBeta);
    jfrm.add(jcbGamma);
    jfrm.add(jbtn);
    jfrm.add(jlabChanged);
    jfrm.add(jlabSelected);
    jfrm.add(jlabSum);

    // Display the frame.
    jfrm.setVisible(true);
  }

  // This is the handler for the check boxes.
  @Override
  public void itemStateChanged(ItemEvent ie) {
    String str = "";

    // Obtain a reference to the check box that caused the event.
    JCheckBox cb = (JCheckBox) ie.getItem();

    // Report what check box changed.
    if (cb.isSelected()) jlabChanged.setText(cb.getText() + " was just selected.");
    else jlabChanged.setText(cb.getText() + " was just cleared.");

    // Report all selected boxes.
    if (jcbAlpha.isSelected()) str += "Alpha ";
    if (jcbBeta.isSelected()) str += "Beta ";
    if (jcbGamma.isSelected()) str += "Gamma";

    jlabSelected.setText("Selected check boxes: " + str);
  }

  @Override
  public void actionPerformed(ActionEvent e) {
    if(jcbAlpha.isSelected()) jlabSum.setText("Try to do something here just for fun ...");
  }

  public static void main(String[] args) {
    // Create the frame on the event dispatching thread.
    SwingUtilities.invokeLater(CBDemo::new);
  }
}
